### PR TITLE
Lm mq bugfix

### PR DESCRIPTION
**Pull request by jared-dtg**
Redo of #6 (little quick on the draw with that merge there ;-) )

Tweaks to match Lisa & Marco's analysis.

Add PAIRED-end filtering, which necessitated adding another shell script. Sadly unavoidable but the right thing to do. 😥

Tested on Lisa's LM1126 BAM. s3://dtg-jared/lisasBug/LM1126.bam

Will post results shortly. Will update readme shortly as well.

@DTGmunding Give it a try on your end, but don't hit merge; I got these numbers from my alignment of your FASTQs:

```
Mapping Quality Threshold         : 40
Read1                             : 4505616
Read2                             : 4440232
Mapped pairs                      : 3915274
PCR dupe pairs                    : 9847
Mapped nondupe pairs              : 3905427
Valid Pairs (cis>1000bp + trans)  : 3517577
Mapped nondupe pairs cis          : 3289426
Mapped nondupe pairs cis <=1000bp : 387850
Mapped nondupe pairs cis >1000bp  : 2901576
Mapped nondupe pairs cis >10000bp : 2157962
Mapped nondupe trans pairs        : 616001
Expected unique pairs at 300M sequencing:  269101956.2
```

### CODE REVIEW

**Comment by DTGmunding** [comment]
Ran vs. @DTGmunding's reference and got:

```

Mapping Quality Threshold         : 40
Read1                             : 4503657
Read2                             : 4438337
Mapped pairs                      : 4496282
PCR dupe pairs                    : 10791
Mapped nondupe pairs              : 4485491
Valid Pairs (cis>1000bp + trans)  : 4070676
Mapped nondupe pairs cis          : 3595961
Mapped nondupe pairs cis <=1000bp : 414815
Mapped nondupe pairs cis >1000bp  : 3181146
Mapped nondupe pairs cis >10000bp : 2380952
Mapped nondupe trans pairs        : 889530
Expected unique pairs at 300M sequencing:  269459529.5
```

**Comment by DTGmunding** [comment]
vs. Jared's reference is:

```
Mapping Quality Threshold         : 40
Read1                             : 4505616
Read2                             : 4440232
Mapped pairs                      : 4498033
PCR dupe pairs                    : 10799
Mapped nondupe pairs              : 4487234
Valid Pairs (cis>1000bp + trans)  : 4072263
Mapped nondupe pairs cis          : 3597987
Mapped nondupe pairs cis <=1000bp : 414971
Mapped nondupe pairs cis >1000bp  : 3183016
Mapped nondupe pairs cis >10000bp : 2382726
Mapped nondupe trans pairs        : 889247
```

**Comment by DTGmunding** [comment]
Running Jared's script vs. Lisa's BAM (without realigning):

```
Mapping Quality Threshold         : 40
Read1                             : 4503657
Read2                             : 4438337
Mapped pairs                      : 4496282
PCR dupe pairs                    : 10791
Mapped nondupe pairs              : 4485491
Valid Pairs (cis>1000bp + trans)  : 4070676
Mapped nondupe pairs cis          : 3595961
Mapped nondupe pairs cis <=1000bp : 414815
Mapped nondupe pairs cis >1000bp  : 3181146
Mapped nondupe pairs cis >10000bp : 2380952
Mapped nondupe trans pairs        : 889530
Expected unique pairs at 300M sequencing:  269459529.5
```

**Comment by jared-dtg** [comment]
And then I ran my script against your BAM without realigning also:

```
Mapping Quality Threshold         : 40
Read1                             : 4503657
Read2                             : 4438337
Mapped pairs                      : 4496282
PCR dupe pairs                    : 10791
Mapped nondupe pairs              : 4485491
Valid Pairs (cis>1000bp + trans)  : 4070676
Mapped nondupe pairs cis          : 3595961
Mapped nondupe pairs cis <=1000bp : 414815
Mapped nondupe pairs cis >1000bp  : 3181146
Mapped nondupe pairs cis >10000bp : 2380952
Mapped nondupe trans pairs        : 889530
```

**Comment by jared-dtg** [comment]
Same numbers when using the same BAM, same samtools version, same samblaster version.

Jared's BWA version is 0.7.17-r1188

**Comment by DTGmunding** [comment]
Lisa's BWA version is:

0.7.17-r1198-dirty

**Comment by DTGmunding** [comment]
OK same numbers on Lisa's machine with Jared's bam.

**Comment by jared-dtg** [comment]
OK, just ran it again multiple times after lots of testing and keep getting good numbers:

```
Mapping Quality Threshold         : 40
Read1                             : 4505616
Read2                             : 4440232
Mapped pairs                      : 3915274
PCR dupe pairs                    : 9847
Mapped nondupe pairs              : 3905427
Valid Pairs (cis>1000bp + trans)  : 3517577
Mapped nondupe pairs cis          : 3289426
Mapped nondupe pairs cis <=1000bp : 387850
Mapped nondupe pairs cis >1000bp  : 2901576
Mapped nondupe pairs cis >10000bp : 2157962
Mapped nondupe trans pairs        : 616001
Expected unique pairs at 300M sequencing:  269101956.2
```

I verified that the version that I ran was exactly the version that is present on this branch:

```
(base) jared@ip-10-0-0-10:omni-c_qc$ git pull origin lm_mq_bugfix
From github.com:dovetail-genomics/omni-c_qc
 * branch            lm_mq_bugfix -> FETCH_HEAD
Already up-to-date.
(base) jared@ip-10-0-0-10:omni-c_qc$ git push origin lm_mq_bugfix
Everything up-to-date
(base) jared@ip-10-0-0-10:omni-c_qc$ git diff
(base) jared@ip-10-0-0-10:omni-c_qc$ 
```

And here's the exact command I ran (from scratch):

```
./omni-c_qc.bash /ref/hg38/GRCh38.p12.fa lisasBug/LM1126_S12_L001_R1_001.fastq.gz lisasBug/LM1126_S12_L001_R2_001.fastq.gz test.bam jm
```

I'm going to try on a fresh instance now for maximum paranoia.

**Comment by steve-dtg** [comment]
Rerun on a fresh environment. Dependencies were installed from the drylab repository using conda.

I am using the reference from s3://doveseq/ref/hg38

```
Mapping Quality Threshold         : 40
Read1                             : 4505616
Read2                             : 4440232
Mapped pairs                      : 4498033
PCR dupe pairs                    : 10799
Mapped nondupe pairs              : 4487234
Valid Pairs (cis>1000bp + trans)  : 4072263
Mapped nondupe pairs cis          : 3597987
Mapped nondupe pairs cis <=1000bp : 414971
Mapped nondupe pairs cis >1000bp  : 3183016
Mapped nondupe pairs cis >10000bp : 2382726
Mapped nondupe trans pairs        : 889247
Expected unique pairs at 300M sequencing:  269101956.2
```

Attached below are my exact dependencies. This is the output of `conda list`.
[list.txt](https://github.com/dovetail-genomics/omni-c_qc/files/3933557/list.txt)

**Comment by mblanche** [comment]
Ok, running from a plain vanilla ubuntu with deps from source, results are: 

(Not sure how to do the table straight from the output of J. script...)

Mapping Quality Threshold         : 40
Read1                             : 4503657
Read2                             : 4438337
Mapped pairs                      : 4496282
PCR dupe pairs                    : 10791
Mapped nondupe pairs              : 4485491
Valid Pairs (cis>1000bp + trans)  : 4070676
Mapped nondupe pairs cis          : 3595961
Mapped nondupe pairs cis <=1000bp : 414815
Mapped nondupe pairs cis >1000bp  : 3181146
Mapped nondupe pairs cis >10000bp : 2380952
Mapped nondupe trans pairs        : 889530
Expected unique pairs at 300M sequencing:  269243896.6

**Comment by mblanche** [comment]
Ok, first thing that is weird looking at the numbers, is 

Mapped pairs : 4496282 > Read2 : 4438337

How's tat possible?

**Comment by mblanche** [comment]
Here's the exact steps to reproduce from a plain vanilla ubuntu box

```sudo apt-get update && sudo apt-get upgrade

sudo apt-get install emacs25-nox

DEBIAN_FRONTEND=noninteractive && \
    sudo apt-get -y install build-essential python python3 python-pip \
	 libgsl-dev libncurses5-dev libbz2-dev liblzma-dev zlib1g-dev
				       

sudo pip install awscli
aws configure
## Enter your credentials

git clone https://github.com/lh3/bwa.git
cd bwa
make -j$(nproc)
sudo cp bwa /usr/local/bin/

cd
wget https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2
tar -xvf samtools-1.10.tar.bz2 
cd samtools-1.10/
./configure
make -j$(nproc)
sudo make install

cd
git clone https://github.com/GregoryFaust/samblaster.git
cd samblaster/
make -j$(nproc)
sudo cp samblaster /usr/local/bin/

cd
wget https://github.com/smithlabcode/preseq/releases/download/v2.0.1/preseq_v2.0.1.tar.bz2
tar xvf preseq_v2.0.1.tar.bz2
cd preseq
make -j$(nproc)
sudo cp preseq /usr/local/bin/

cd
git clone https://github.com/dovetail-genomics/omni-c_qc.git
cd omni-c_qc/

git checkout origin/lm_mq_bugfix



aws s3 cp s3://dtg-jared/lisasBug/LM1126_S12_L001_R1_001.fastq.gz .
aws s3 cp s3://dtg-jared/lisasBug/LM1126_S12_L001_R2_001.fastq.gz .

mkdir bwaIndex
cd bwaIndex
aws s3 cp s3://tower-ops/marco/ebs/hg38/hg38.fa .
aws s3 cp s3://tower-ops/marco/ebs/hg38/hg38.amb .
aws s3 cp s3://tower-ops/marco/ebs/hg38/hg38.ann .
aws s3 cp s3://tower-ops/marco/ebs/hg38/hg38.bwt .
aws s3 cp s3://tower-ops/marco/ebs/hg38/hg38.pac .
aws s3 cp s3://tower-ops/marco/ebs/hg38/hg38.sa .


cd ..
./omni-c_qc.bash bwaIndex/hg38 LM1126_S12_L001_R1_001.fastq.gz LM1126_S12_L001_R2_001.fastq.gz LM1126.bam test
```

**Comment by jared-dtg** [comment]
Thanks all! It’s mystifying to me how I’m getting the right numbers, when both Marco and Steve got very similar wrong ones, even with slightly different references and software versions.

Good catch on that discrepancy between read2 and mapped pairs.

Now that I can reproduce the error (and indeed investigate the differences in things like the BAM file, line by line), I should be able to nail it shortly.

**Comment by jared-dtg** [comment]
Ok getting happy numbers now in the same environment where @steve-dtg got bad ones.

```
Mapping Quality Threshold         : 40
Read1                             : 4505616
Read2                             : 4440232
Mapped pairs                      : 3915274
PCR dupe pairs                    : 9847
Mapped nondupe pairs              : 3905427
Valid Pairs (cis>1000bp + trans)  : 3517577
Mapped nondupe pairs cis          : 3289426
Mapped nondupe pairs cis <=1000bp : 387850
Mapped nondupe pairs cis >1000bp  : 2901576
Mapped nondupe pairs cis >10000bp : 2157962
Mapped nondupe trans pairs        : 616001
Expected unique pairs at 300M sequencing:  269101956.2
```

The (hopeful 🤞)  fix was here: d0273c8d26


```
qualthresh=40
mate_filter_cmd="perl -ne 'm/MQ:i:(\\d+)/; if (\$1 >= \$ENV{qualthresh}) { print; }'"
```

changed to:

`mate_filter_cmd="perl -e 'while (<STDIN>) { m/MQ:i:(\\d+)/; if (\$1 >= \$ARGV[0]) { print; }}' $qualthresh"`


The problem was bash foolishness -- I didn't "export" `$qualthresh`, so it wasn't actually getting passed to the perl one-liner (effectively qualthresh=0 I think). In **my shell**  though, I happened to have `$qualthresh` exported because I first ran that one-liner directly. Upon logging out and logging in again, I started seeing the error myself!

I'm testing a few different ways now. If at least a couple of you could pull the latest and run it one more time to confirm that you're also seeing 3.9 million mapped nondupe pairs, I'd really appreciate it. Then we can merge the PR.

**Comment by mblanche** [comment]
Shoot... I had notice you usage of ENV{} in your perl one liner which is why I asked about it Thursday... when you took over, I was rewriting that on Lisa’s computer. 

Sorry, should have mentioned it. 

Glad you found it!

**Comment by DTGmunding** [comment]
Yes! now I am happy! Can you please merge with master and I will do a final final final test on a new dataset using just the master commands.

Mapping Quality Threshold         : 40
Read1                             : 4503657
Read2                             : 4438337
Mapped pairs                      : 3913449
PCR dupe pairs                    : 9841
Mapped nondupe pairs              : 3903608
Valid Pairs (cis>1000bp + trans)  : 3515874
Mapped nondupe pairs cis          : 3287765
Mapped nondupe pairs cis <=1000bp : 387734
Mapped nondupe pairs cis >1000bp  : 2900031
Mapped nondupe pairs cis >10000bp : 2156470
Mapped nondupe trans pairs        : 615843
Expected unique pairs at 300M sequencing:  269459529.5

**Comment by jared-dtg** [comment]
🥳
Merging.

**Pull request merged**
